# -*- coding: utf-8 -*-
"""Design_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ICVZNe--2phDBwwqiMNHf2SEI9JRGSm6
"""

from google.colab import drive
drive.mount('/content/drive')

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models
import torch.optim as optim
from torch.optim import lr_scheduler
from torch.utils import data
import numpy as np
import torchvision
from  numpy import exp,absolute
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
import time
import os
import copy
import math
from sklearn import svm
import sklearn.model_selection as model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score,precision_score ,recall_score
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.metrics.pairwise import euclidean_distances
from PIL import Image
import cv2
from skimage.feature import local_binary_pattern
import random
import glob
import pickle

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

num_classes = 2

data_transforms = transforms.Compose([
    transforms.Resize([224, 224]),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
lbp_transforms = transforms.Compose([
    transforms.Resize([224, 224]),
    transforms.Grayscale(num_output_channels=1),  # Convert images to grayscale
    transforms.ToTensor(),
    transforms.Normalize([0.485], [0.229])  # Normalization for grayscale images
])
gray_transform = transforms.Grayscale(num_output_channels=1)

class LBPNet(nn.Module):
    def __init__(self, num_classes):
        super(LBPNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
        self.relu1 = nn.ReLU()
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
        self.relu2 = nn.ReLU()
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)
        self.fc1 = nn.Linear(64 * 56 * 56, 512)
        self.relu3 = nn.ReLU()
        self.fc2 = nn.Linear(512, num_classes)

    def forward(self, x):
        x = self.conv1(x)
        x = self.relu1(x)
        x = self.pool1(x)
        x = self.conv2(x)
        x = self.relu2(x)
        x = self.pool2(x)
        x = x.view(x.size(0), -1)
        x = self.fc1(x)
        x = self.relu3(x)
        x = self.fc2(x)
        return x

def get_model1():
    densenet = torchvision.models.densenet161(pretrained=True)
    # Freeze all the layers except the last few layers
    for param in densenet.parameters():
       param.requires_grad = False
    #densenet.classifier = nn.Sequential(nn.Linear(2208, 512), nn.ReLU(), nn.Linear(512, num_classes), nn.Sigmoid())
    densenet.classifier = nn.Sequential(nn.Linear(2208, num_classes),nn.Sigmoid())
    densenet = densenet.to(device)
    return densenet

def get_model3():
    resnet = torchvision.models.resnet50(pretrained=True)
    # Freeze all the layers except the last few layers
    for param in resnet.parameters():
       param.requires_grad = False
    resnet.fc = nn.Linear(2048,num_classes)
    resnet = resnet.to(device)
    return resnet

def get_LBP():
    lbp_net = LBPNet(num_classes)  # Create an instance of LBPNet
    # Move model to the device
    lbp_net = lbp_net.to(device)
    return lbp_net

model1 = get_model1()
    model1.load_state_dict(torch.load('/content/drive/MyDrive/DataSets/Save_Models/model1.pth'))
    model1.eval()

    model3 = get_model3()
    model3.load_state_dict(torch.load('/content/drive/MyDrive/DataSets/Save_Models/model3.pth'))
    model3.eval()

    model9 = get_LBP()
    model9.load_state_dict(torch.load('/content/drive/MyDrive/DataSets/Save_Models/model9.pth'))
    model9.eval()

    model_path = '/content/drive/MyDrive/DataSets/Save_Models/svm.pk1'
    with open(model_path, 'rb') as file:
      clf = pickle.load(file)

#Listing Trained Models
def get_models(m1,m2,m3):
    return [m1,m2,m3]

def PreProcess_img(input):
  img = cv2.imread(input)
  img = cv2.resize(img, (224, 224))
  img = transforms.ToTensor()(img)
  img = transforms.Normalize(mean=[0.485, 0.456, 0.406],std=[0.229, 0.224, 0.225])(img)

  # Add batch dimension
  img = img.unsqueeze(0)
  img = img.to(device) #send tensor to GPU
  return img

models = get_models(model1,model3,model9)
#modelsvm = get_models(model1,clf,model9)

def extract_features(model,image):
    with torch.no_grad():
        features = model(image)
    return features

def extract(models,image):
  Feature = []
  for model in models:
    if model is model9:
      img = gray_transform(image)
      feature = extract_features(model,img)
    else:
      feature = extract_features(model,image)
    Feature.append(feature)
  return Feature

def compare_features(features1, features2):
    # Compute euclidean distance between feature vectors
    similarity = euclidean_distances(features1, features2)
    return similarity

def Return_SinglePredClass(model,image,feat_l,feat_r,th):

  x = 1
  #image = PreProcess_img(image)
  Feat = extract_features(model,image)
  #for i in range(len(Feat)):
  s_left = compare_features(Feat.cpu().numpy(), feat_l.cpu().numpy())
  s_right = compare_features(Feat.cpu().numpy(), feat_r.cpu().numpy())

  #print(Feat," ",s_left," ",s_right)
  if(s_left < s_right):
    if s_left < th:
      x = x - 1
    #else:
      #print("Left hand: Match not found")
  else:
    if s_right < th:
      x = x - 1
    #else:
      #print("Right hand: Match not found")

  return x

def returnPredList(models,image,Features1,Features2,threshold):
  PredList = []
  for model in models:
    if model is model9:
      img = gray_transform(image)
      p = Return_SinglePredClass(model,img,Features1[2],Features2[2],threshold[2])
    if model is model3:
      p = Return_SinglePredClass(model,image,Features1[1],Features2[1],threshold[1])
    if model is model1:
      p = Return_SinglePredClass(model,image,Features1[0],Features2[0],threshold[0])
    PredList.append(p)
  return PredList

def returnPredClass(list):
  r = 0
  n = len(list)
  for i in range(n):
    if(list[i] == 0):
      r = r + 1
  if (r >= 2):
    return 0;
  else:
    return 1;

### USER INPUT for REGISTRATION ###
### THRESHOLD CALCULATION ###
subject = "043-M"
input_image_path = '/content/drive/MyDrive/DataSets/Palmvein_h/Registration'
th = 0
frr = 0
sfar = 0
threshold = [0.3,0.3,1.0]

for root, dirs, files in os.walk(input_image_path):
    if os.path.basename(root) == subject:       #change Subject/User as necessary
        print(root)
        for subdir in dirs:
            if subdir == "enrol":
                subdir_path = os.path.join(root, subdir)
                image_files = glob.glob(os.path.join(subdir_path, '*.png'))
                for image_file in image_files:
                  if image_file.endswith("_L_1_1.png"):
                    image = PreProcess_img(image_file)
                    Features1 = extract(models,image)
                  elif image_file.endswith("_R_1_1.png"):
                    image = PreProcess_img(image_file)
                    Features2 = extract(models,image)
                print("Threshold Features for Subject ",os.path.basename(root),"are:",Features1," and ",Features2)
                print("Threshold Value for Similarity check is ",threshold)

### TESTING: SAME SUBJECT, REMAINING IMAGES ###
print("Remaining Images Test")
for root, dirs, files in os.walk(input_image_path):
    if os.path.basename(root) == subject:       #change Subject/User as necessary
        for subdir in dirs:
            if subdir == "probe_spoof":
                subdir_path = os.path.join(root, subdir)
                #print(subdir_path)
                image_files = glob.glob(os.path.join(subdir_path, '*.png'))
                for image_file in image_files:
                    image = PreProcess_img(image_file)
                    pred = returnPredList(models,image,Features1,Features2,threshold)
                    predClass = returnPredClass(pred)
                    #for i in range(len(score)):
                    if (predClass == 0):
                      print("Image Accepted. Same Subject ",os.path.basename(root))
                      sfar = sfar + 1
                    else:
                        print("Image Rejected. Try Again")
                print("Spoof Probes Accepted:", sfar)
                print("SFAR% for Same User is:", sfar/len(image_files))
                sfar = 0
            elif subdir == "probe_real":
                subdir_path = os.path.join(root, subdir)
                #print(subdir_path)
                image_files = glob.glob(os.path.join(subdir_path, '*.png'))
                for image_file in image_files:
                    image = PreProcess_img(image_file)
                    pred = returnPredList(models,image,Features1,Features2,threshold)
                    predClass = returnPredClass(pred)
                    #for i in range(len(score)):
                    if (predClass == 0):
                        print("Image Accepted. Same Subject ",os.path.basename(root))
                    else:
                        print("Image Rejected. Try Again")
                        frr = frr + 1
                print("Genuine Probes Rejected:", frr)
                print("FRR% for Same User is:", frr/len(image_files))
                frr = 0
            else:
                continue

### USER INPUT SUBJECT's RESULTS with OTHER SUBJECT's IMAGES ###
import warnings
warnings.filterwarnings("ignore")

#subject = "002-M"
input_image_path = '/content/drive/MyDrive/DataSets/Palmvein_h/Registration'

i = 0
far = 0
sfar = 0
len_rcount = 0
len_scount = 0

for root, dirs, files in os.walk(input_image_path):
    if os.path.basename(root) != subject:       #change Subject/User as necessary
        #print(root)  #other Subjects
        for subdir in dirs:
            if subdir == "probe_real":
                subdir_path = os.path.join(root, subdir)
                image_files = glob.glob(os.path.join(subdir_path, '*.png'))
                for image_file in image_files:
                    image = PreProcess_img(image_file)
                    pred = returnPredList(models,image,Features1,Features2,threshold)
                    predClass = returnPredClass(pred)
                    #for i in range(len(score)):
                    if (predClass == 0):
                        #print("Image Accepted. Subject ",os.path.basename(root))
                        far = far + 1
                    else:
                        #print("Image Rejected. Try Again")
                        a = 0
                len_rcount = len_rcount + len(image_files)
            elif subdir == "probe_spoof":
                subdir_path = os.path.join(root, subdir)
                image_files = glob.glob(os.path.join(subdir_path, '*.png'))
                for image_file in image_files:
                    pred = returnPredList(models,image,Features1,Features2,threshold)
                    predClass = returnPredClass(pred)
                    #for i in range(len(score)):
                    if (predClass == 0):
                        #print("Image Accepted. Subject ",os.path.basename(root))
                        sfar = sfar + 1
                    else:
                        #print("Image Rejected. Try Again")
                        a = 0
                len_scount = len_scount + len(image_files)

print("Total Real Inputs of Other Subjects: ", len_rcount)
print("Genuine Attacks Accepted:", far)
print("FAR% for Other Users is:", far * 100 / len_rcount)
print("Total Spoof Inputs of Other Subjects: ", len_scount)
print("Spoof Probes Accepted:", sfar)
print("SFAR% for Other Users is:", sfar * 100 / len_scount)
eer = ((far / len_rcount) + (sfar / len_scount)) / 2
print("EER % is:", eer * 100)



#img_path = "/content/drive/MyDrive/DataSets/Palmvein_h/test/probe/nom/041_R_2_4.png"
#img_path = "/content/drive/MyDrive/DataSets/Palmvein_h/Registration/043-M/probe_spoof/043_R_2_2.png"
#img_path = "/content/drive/MyDrive/DataSets/Palmvein_h/Registration/001-M/probe_real/001_R_1_4.png"
img_path = "/content/drive/MyDrive/DataSets/Palmvein_h/Registration/043-M/probe_real/043_L_1_4.png"

print(img_path)
test = PreProcess_img(img_path)
pr = returnPredList(models,test,Features1,Features2,threshold)
pC = returnPredClass(pr)